### ISSUE TITLE
The builder should be configured via environment variables, not by app.yaml

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/runtime-builder-java#37]
- the builder should not look for app.yaml in the included sources
- configuration should be passed via environment variables
- configuration should be optional

**Comment by aslo** [comment]
Update: configuration should be taken from a file whose path will be passed to the builder in the environment variable `$GAE_APPLICATION_YAML_PATH`

**Comment by meltsufin** [comment]
We should be careful not to lock the builder into being an AE product. So, this could be supplemental, but not exclusive to get config.

**Comment by aslo** [comment]
This is obsoleted by #58.

**Comment by meltsufin** [comment]
I don't think #58 really makes it obsolete because it still requires the presence of `app.yaml`.

**Comment by aslo** [comment]
Maybe "obsolete" wasn't the best word to use, but the direction that the builders are moving in, for now, is to what we're doing in #58 - using a yaml file whose path is provided by an environment variable. The file need not necessarily be named "app.yaml", as long as it contains builder configuration in the runtime_config (and soon, lifecycle) fields.

**Comment by meltsufin** [comment]
We might want to think about letting the user provide configuration via command-line arguments rather than the `app.yaml` or at least make `app.yaml` optional for instances where default configuration is sufficient.

**Comment by aslo** [comment]
Marking as complete. Issue #79 is a more generic issue that addresses this.
