### ISSUE TITLE
Base runtimes should all support adding applications to the same path

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/runtime-builder-java#4]
It's a good idea to add this to the contract between the builder and any supported base runtimes. This will make it easier to support additional base runtimes in the future.

**Comment by meltsufin** [comment]
Agreed, and ideally, it would just be the current directory.
```Dockerfile
ADD my-app.war .
```

**Comment by aslo** [comment]
This is completed. The openjdk, jetty, and tomcat runtimes all support the `$APP_DESTINATION` environment variable.
