### ISSUE TITLE
Add support for the jetty9-compat image

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/runtime-builder-java#47]
If an exploded WAR is detected, we should use that image.

**Comment by meltsufin** [comment]
I think we should be a bit more precise in deciding to use the compat image, if at all possible. I think there is something in the `app.yaml` that we can read to determine if compat is requested.

**Comment by aslo** [comment]
SGTM

**Comment by aslo** [comment]
Just to close the loop on this - I don't believe there is currently any option in app.yaml that allows users to manually select compat. As such I'm OK with leaving this out for now.

@meltsufin If you think that's important to add, feel free to create an issue and assign to me.

**Comment by meltsufin** [comment]
```
beta_settings:
  enable_app_engine_apis: true
```
Can be used to indicate compat.

**Comment by aslo** [comment]
Ah, okay. Let's leave this ticket open until that's supported.
