### ISSUE TITLE
"runtime_config: server: tomcat" doesn't work

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/runtime-builder-java#68]
This configuration:

```yaml
runtime_config:
  server: tomcat
```
should select the Tomcat base image, but it currently gets rejected.
```
Step #0: Exception in thread "main" java.lang.IllegalArgumentException: Invalid jdk/server combination: *|tomcat
Step #0:        at com.google.cloud.runtimes.builder.config.domain.JdkServerLookup.lookupServerImage(JdkServerLookup.java:113)
Step #0:        at com.google.cloud.runtimes.builder.buildsteps.docker.DefaultDockerfileGenerator.generateDockerfile(DefaultDockerfileGenerator.java:57)
Step #0:        at com.google.cloud.runtimes.builder.buildsteps.docker.StageDockerArtifactBuildStep.doBuild(StageDockerArtifactBuildStep.java:92)
Step #0:        at com.google.cloud.runtimes.builder.buildsteps.base.BuildStep.run(BuildStep.java:52)
Step #0:        at com.google.cloud.runtimes.builder.BuildPipeline.build(BuildPipeline.java:62)
Step #0:        at com.google.cloud.runtimes.builder.Application.build(Application.java:81)
Step #0:        at com.google.cloud.runtimes.builder.Application.main(Application.jav
```

The readme does say that the server should be `tomcat8` or `jetty9`, but that seems to contradict the original design and simplicity in configuration.

_Edit: I originally thought it selected Jetty rather than Tomcat, but it actually just didn't deploy at all when selecting `server: tomcat`_.

**Comment by aslo** [comment]
Good point. This wasn't something we originally designed for but, `server: tomcat` should definitely just map to `tomcat:latest` (probably the same should apply for `server: jetty`.

It's also probably a good idea to print the full list of valid server/jdk lookups in addition to the stack trace.
