### ISSUE TITLE
Support exploded WAR deployments in Jetty and Tomcat runtimes

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/runtime-builder-java#69]
The jetty runtime currently has only been tested with WAR file deployments, which are extracted at container start time.  In theory, exploded WARs should be added to the `/app` directory (which is symlinked to  `$JETTY_BASE/webapps/root`).

**Comment by meltsufin** [comment]
Duplicate of #44?

**Comment by aslo** [comment]
Yep! Feel free to close one of them.
