### ISSUE TITLE
Implement configuration mechanism for non-App Engine use

### ISSUE THREAD

**Issue by aslo** [GoogleCloudPlatform/runtime-builder-java#79]
Currently, the only way to pass configuration to the builder is via the runtime_config section of an app.yaml file that is within the directory that the builder is operating on.  This is only appropriate for App Engine deployments, therefore we need a more generic mechanism

**Comment by meltsufin** [comment]
Just to clarify, in the offline discussion, we decided to just add command-line arguments for the additional configuration, such as  `artifact`, `build_script`, and `jetty_quickstart`.

For invoking through the container builder, we will enable [substitutions](https://cloud.google.com/container-builder/docs/concepts/build-requests#substitutions) in `java.yaml` to pass in the same configuration variables to the builder, again as command-line arguments.

@ChengyuanZhao
