### ISSUE TITLE
runtime builder should not inherit from dockerhub's openjdk image.

### ISSUE THREAD

**Issue by sharifelgamal** [GoogleCloudPlatform/runtime-builder-java#92]
Currently, this image uses gcr.io/cloud-builders/mvn as its base image, which itself uses dockerhub's openjdk image. We should be inheriting from GCP's openjdk image so that we can safely monitor this image for security vulnerabilities.

**Comment by meltsufin** [comment]
@ChengyuanZhao, please take a look when we come back from the conf.

**Comment by ChengyuanZhao** [comment]
Still a bit of a docker novice, but it doesn't seem like we can swap out that underlying openjdk:8-jdk image for our version of it here since we're using the already-built image at gcr.io/cloud-builders/mvn that ultimately uses that openjdk image. 

Would it be out of the question to make the change in the GoogleCloudPlatoform/cloud-builders repo to either add another version of that image or just change it to use our gcr.io/google-appengine/openjdk:8 image?

**Comment by meltsufin** [comment]
If this suggestion is not an option, we can just set our base image to `gcr.io/google-appengine/openjdk:8` and install all the necessary components, i.e. Maven, in our own builder Dockerfile.

**Comment by ChengyuanZhao** [comment]
Oh ok, but wouldn't switching the cloud-builders mvn image to use our openjdk:8 be better since it avoids all that duplication? I'm inferring that is not going to be possible then?

**Comment by sharifelgamal** [comment]
We can potentially ask cloud-builders to use our openjdk image, but it would be safer to build a minimal maven image based on our openjdk anyway, to avoid unnecessary outside dependencies.

**Comment by ChengyuanZhao** [comment]
Please take a look at the linked issue in the cloud-builders repo and the associated PR https://github.com/GoogleCloudPlatform/cloud-builders/pull/165

**Comment by sharifelgamal** [comment]
Excellent, I'll close this when that PR gets merged in. We will also need to rebuild the mvn image then this one.

**Comment by sharifelgamal** [comment]
The mvn image should be updated, all you should have to do is rebuilt this image and it'll be good to go.

**Comment by meltsufin** [comment]
@ChengyuanZhao Can you please rebuild the builder image? Thanks!

**Comment by ChengyuanZhao** [comment]
Yup I had started one and it's in progress.

**Comment by sharifelgamal** [comment]
Looks good.
